apiVersion: v1
kind: Service
metadata:
  name: log-app-service
spec:
  type: LoadBalancer # Docker Desktop - localhost:8081
  selector:
    app: log-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081