apiVersion: apps/v1  # [수정] v1.1 -> v1
kind: Deployment
metadata:
  name: log-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-app
  template:
    metadata:
      labels:
        app: log-app
    spec:
      containers:
        - name: log-app
          image: soyunju/logcollector-app:latest
          # Always / IfNotPresent / Never
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"

            # 2. LC DB
            - name: SPRING_LC_DATASOURCE_URL
              value: jdbc:mariadb://lc-db-mariadb:3306/logcollector
            - name: SPRING_LC_DATASOURCE_USERNAME
              value: root
            - name: SPRING_LC_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logcollector-secrets
                  key: db-root-password

            # 3. KB DB
            - name: SPRING_KB_DATASOURCE_URL
              value: jdbc:mariadb://lc-db-mariadb:3306/knowledge_base
            - name: SPRING_KB_DATASOURCE_USERNAME
              value: kb_root
            - name: SPRING_KB_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logcollector-secrets
                  key: db-root-password

            # 4. Redis
            - name: SPRING_REDIS_HOST
              value: lc-redis-master
            - name: SPRING_REDIS_PORT
              value: "6379"

            # 5. OpenAI API Key
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: logcollector-secrets
                  key: openai-api-key

          resources:
            requests:
              memory: "512Mi"   # 최소
              cpu: "250m"       # CPU 0.25
            limits:
              memory: "1Gi"     # 최대값 강제 종료
              cpu: "500m"       # CPU 0.5

          # Liveness: 생존 확인, Readiness: 준비 확인
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10       # 10초마다 검사
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 5