apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-app
  template:
    metadata:
      labels:
        app: log-app
    spec:
      containers:
        - name: log-app
          image: soyunju/logcollector-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_LC_DATASOURCE_URL
              value: jdbc:mariadb://lc-db-mariadb:3306/logcollector
            - name: SPRING_LC_DATASOURCE_USERNAME
              value: root
            - name: SPRING_LC_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logcollector-secrets
                  key: db-root-password
            - name: SPRING_KB_DATASOURCE_URL
              value: jdbc:mariadb://lc-db-mariadb:3306/knowledge_base
            - name: SPRING_KB_DATASOURCE_USERNAME
              value: kb_root
            - name: SPRING_KB_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logcollector-secrets
                  key: db-root-password
            - name: SPRING_REDIS_HOST
              value: lc-redis-master
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: logcollector-secrets
                  key: openai-api-key

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

          # Start (최대 300초)
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            failureThreshold: 30
            periodSeconds: 10

          # 생존 확인
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          # 트래픽
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5