apiVersion: v1
kind: Service
metadata:
  name: log-app-service
  labels:
    app: log-app
spec:
  type: ClusterIP
  selector:
    app: log-app
  ports:
    - name: http-web
      port: 80
      targetPort: 8080