apiVersion: v1
kind: Service
metadata:
  name: log-app-service
  labels:
    app: log-app
spec:
  type: LoadBalancer
  selector:
    app: log-app
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
