apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: log-app
  namespace: default
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: log-app            # svc log-app-service labels.app 과 일치
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http              # svc 포트 name: http 와 일치
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
